global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'apollo-gateway'
    static_configs:
      - targets: ['apollo-gateway:4000']
    metrics_path: /metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
